# Generated by Django 2.1 on 2018-08-15 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('HangmanGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='sessao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AlterField(
            model_name='palavra',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentário, informações adicionais'),
        ),
        migrations.AlterField(
            model_name='palavra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
