# Generated by Django 2.1 on 2018-09-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangmanGame', '0003_auto_20180813_1216'),
        ('HangmanGame', '0002_auto_20180815_0109'),
    ]

    operations = [
    ]
